version: '3.8'

services:
  apache:
    image: oksesaneka22/site2223:latest
    deploy:
      replicas: 1
    ports:
      - "8081:80"
    networks:
      - webnet

  wordpress:
    image: oksesaneka22/nginx:latest
    deploy:
      replicas: 1
    ports:
      - "8082:80"
    networks:
      - webnet

  tomcat:
    image: oksesaneka22/nginx:animation2
    deploy:
      replicas: 1
    ports:
      - "8083:8080"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet:
    driver: overlay

configs:
  nginx_conf:
    external: true
