version: '3.8'

services:
  apache:
    image: oksesaneka22/site223:latest
    container_name: site
    restart: always
    ports:
      - "8081:80"
    networks:
      - webnet

  wordpress:
    image: oksesaneka22/nginx:latest
    container_name: a1
    restart: always
    ports:
      - "8082:80"
    networks:
      - webnet

  tomcat:
    image: oksesaneka22/nginx:animation2
    container_name: a2
    restart: always
    ports:
      - "8083:80"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet:
